### PR TITLE
Fix maps

### LINKED ISSUE #758: Fix maps
MapPage is broken. I think this is a minor styles-related issue.

There is a larger issue with `EditUserLocationMap` - it reloads when typing and flyTo when selection a location doesn't work well.

### PR DESCRIPTION
**Pull request by lucaslcode**
Fixes #758 and some related stuff

I noticed the search box doesn't say "No results" when there are no results, but I couldn't get it to work.

### CODE REVIEW

File: app/frontend/src/components/Map.tsx [hunk 1]
```diff
@@ -69,8 +67,11 @@ export default function Map({
     return { url };
   };
 
+  const mapRef = useRef<mapboxgl.Map>();
   useEffect(() => {
     if (!containerRef.current) return;
+    //don't create a new map if it exists already
+    if (mapRef.current) return;
```
Comment (lucaslcode) [inline app/frontend/src/components/Map.tsx:74]: This is an "easy" solution, but I'm not sure it's really the most correct solution.

Comment (darrenvong) [reply app/frontend/src/components/Map.tsx:74]: Is this because it gets re-run on re-renders? Does this `useEffect` need to run more than once? I guess most of the dependencies are probably messing this up as they are mostly objects/functions...

**Review by darrenvong — COMMENTED** [review]
The URLs on the purple markers are broken. When I clicked on one, I get something like this in the URL:

`https://5cf873bb--frontend.preview.coucher.org/guide/:pageId/:pageSlug?/21/edinburgh`

Oh I think it's because the places and guide route helpers are broken.

File: app/frontend/src/components/Map.tsx (hunk 1 above)
Comment (lucaslcode) [reply app/frontend/src/components/Map.tsx:74]: Honestly, I'm not really sure what was happening. I tried making sure all the dependencies were using `useCallback` but it didn't help. I used a dependency tracking hook and it said that map had a first render every time I typed, but in that case, why were more and more maps being added to the same div? Maybe because they originate from outside react?

Comment (lucaslcode) [reply app/frontend/src/components/Map.tsx:74]: But this is working so 🤷🏻

**Review by darrenvong — APPROVED** [review]
