### PR TITLE
fix: saving simplified user address

### LINKED ISSUE #559: Address clean up from Nominatim
In the legacy vue frontend, we stripped some parts of the address from Nominatim:

https://github.com/Couchers-org/couchers/blob/f95e212833a84d9c470e73530f78587676befc02/app/vue/src/components/EditableLocation.vue#L316-L334

This makes the display addresses a bunch nicer, so instead of:

```
Forbes Street, Macdonaldtown, Newtown, Sydney, Council of the City of Sydney, New South Wales, 2006, Australia
500, West 120th Street, Morningside Heights, Manhattan Community Board 9, Manhattan, New York County, New York, 10027, United States
```

We have:

```
Macdonaldtown, Sydney, Australia
Morningside Heights, Manhattan, New York, United States
```

### PR DESCRIPTION
**Pull request by Tay0108**
Closes #559.

### CODE REVIEW

File: app/frontend/src/components/MapSearch.tsx [hunk 1]
```diff
@@ -78,13 +81,17 @@ export default function MapSearch({
...
+
       setSearchOptions(
-        data.map((obj) => ({
-          name: obj["display_name"],
-          location: new LngLat(Number(obj["lon"]), Number(obj["lat"])),
-        }))
+        nominatimResults.map((result) => {
+          return {
+            name: result["display_name"],
+            simplifiedName: simplifyPlaceDisplayName(result),
```
Comment (lucaslcode) [inline app/frontend/src/components/MapSearch.tsx:91]: This is much better! I would be up for just ditching the full name and using only `name: simplifyPlaceDisplayName(result)` so the list of options has the better-looking name too. Up to you!

File: app/frontend/src/utils/nominatim.ts [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+}
+
+export const simplifyPlaceDisplayName = (place: NominatimPlace) => {
+  const addressFields = [
+    "neighbourhood",
+    "suburb",
+    "city",
+    "country",
+    "town",
+    "village",
```
Comment (lucaslcode) [inline app/frontend/src/utils/nominatim.ts]:
```suggestion
    "town",
    "village",
    "neighbourhood",
    "suburb",
    "city",
    "state",
    "country",
```
How about this? Town and village should be first, and in many places like the US and Australia including the state is important. I just hope it is omitted automatically by nominatim where appropriate😓

**Review by lucaslcode — CHANGES_REQUESTED** [review]
Nice job

File: app/frontend/src/utils/nominatim.ts (hunk 2 above)
Comment (lucaslcode) [reply app/frontend/src/utils/nominatim.ts]: Are villages smaller than towns? Maybe that should be swapped.

Comment (Tay0108) [reply app/frontend/src/utils/nominatim.ts]: From what I know villages are smaller ;) Will swap it ;)

File: app/frontend/src/components/MapSearch.tsx (hunk 1 above)
Comment (Tay0108) [reply app/frontend/src/components/MapSearch.tsx:91]: Wanted to do that but the problem with this approach is that nominatim is still doing search on fields we are not including. The result could be e.g. displaying "Sela" after typing "fa" because there is railway containing "fa". It could be missleading for users. There is a`zoom` query param which we can use to narrow search (https://nominatim.openstreetmap.org/ui/reverse.html?format=html&lat=51.484622236435&lon=8.337727189064&zoom=14) but still there would be cases that there is something we don't want in options list.
image

File: app/frontend/src/utils/nominatim.ts (hunk 2 above)
Comment (Tay0108) [reply app/frontend/src/utils/nominatim.ts]: Should the city be in front of neighbourhood & suburb?

File: app/frontend/src/components/MapSearch.tsx (hunk 1 above)
Comment (Tay0108) [reply app/frontend/src/components/MapSearch.tsx:91]: Or maybe we can do filtering on our end?

Comment (aapeliv) [reply app/frontend/src/components/MapSearch.tsx:91]: In the vue frontend, the autocomplete/search list was raw nominatim output, but then in the automatically generated "display address" box we'd put the culled one

File: app/frontend/src/utils/nominatim.ts (hunk 2 above)
Comment (lucaslcode) [reply app/frontend/src/utils/nominatim.ts]: Cities are bigger imo

File: app/frontend/src/components/MapSearch.tsx (hunk 1 above)
Comment (lucaslcode) [reply app/frontend/src/components/MapSearch.tsx:91]: I see, perhaps leave this then

**Review by lucaslcode — APPROVED** [review]
