### PR TITLE
Fix hydration issue, more landing page adjustments

### LINKED ISSUE #6268: Name not showing when remove friend is selected
Subject: Name not showing when remove friend is selected 
Description:
See screenshot 

Results:

Backend version: develop-194ec110
Frontend version: develop-194ec110
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36
Screen resolution: 395x811
Page: https://couchers.org/connections
User: [@chrisk](https://couchers.org/user/chrisk) (34148)

### PR DESCRIPTION
**Pull request by nabramow**
* Fixes hydration issue caused by CouchersLogo
* Remove changes to `client.ts` since they didn't help
* Make design changes suggested by Marta
* Add LanguagePicker back to the LoggedOut navigation bar
* Closes #6268

**Web frontend checklist**
- [ x ] Formatted my code with `yarn format`
- [ x ] There are no warnings from `yarn lint --fix`
- [ x ] There are no console warnings when running the app
- [ ] Added tests where relevant
- [ x ] All tests pass
- [ x ] Clicked around my changes running locally and it works
- [ x ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

File: app/web/resources/CouchersLogo.tsx [hunk 1]
```diff
@@ -2,15 +2,12 @@ import { styled, SvgIcon } from "@mui/material";
 import Link from "next/link";
 import { baseRoute } from "routes";
 
-const Root = styled("a")(({ theme }) => ({
-  display: "flex",
-  position: "relative",
-}));
-
```
Comment (nabramow) [inline app/web/resources/CouchersLogo.tsx:9]: This was the hydration issue. I removed the `legacyBehavior` from the NextLink below and it didn't need/like an `a` element in it anymore.

File: app/web/components/MapAnimation.tsx [hunk 2]
```diff
@@ -4,21 +4,32 @@ import { LANDING } from "i18n/namespaces";
...
+});
+
+const Attribution = styled("div")({
+  position: "absolute",
+  bottom: 8,
+  right: 10,
+  background: "rgba(255,255,255,0.8)",
+  padding: "2px 8px",
+  borderRadius: 4,
+  fontFamily: "Inter, sans-serif",
```
Comment (aapeliv) [inline app/web/components/MapAnimation.tsx]: We don't have this font, and we shouldn't add a font just for this. Let's just use ubuntu?

**Review by aapeliv — COMMENTED** [review]
otherwise looks good

**Review by aapeliv — APPROVED** [review]
