### PR TITLE
Fix jail not loading

### LINKED ISSUE #373: Jail page is not loading
When the user signs in and is in jail, the page is current blank.

From an initial glance, it looks like it's because the jail route is wrapped in a `PrivateRoute` and when you are in jail, the `PrivateRoute` tries to redirect you to the jail route. I haven't had enough time to look into a proper fix but hope this helps narrows things down a bit least...

### PR DESCRIPTION
**Pull request by lucaslcode**
Closes #373 

This was due to the Route component in PrivateRoute changing from using children to the render pro. Before this, I didn't realise putting jail in a private route had a stray Redirect to itself, since the rest was being rendered anyway.

### CODE REVIEW

**Comment by darrenvong** [comment]
I noticed that jailed users also can't log out at the moment. Since it's related to the bug, we may as well address it here too?

File: app/frontend/src/features/auth/Logout.tsx [hunk 1]
```diff
@@ -1,6 +1,9 @@
+import React from "react";
 import { useEffect } from "react";
```
Comment (darrenvong) [inline app/frontend/src/features/auth/Logout.tsx]:
```suggestion
import React, { useEffect } from "react";
```

**Review by darrenvong — CHANGES_REQUESTED** [review]
Only a minor thing, happy to approve after!

**Review by darrenvong — APPROVED** [review]
