### PR TITLE
Various fixes

### LINKED ISSUE #6456: location cut off on profile link on dashboard on mobile
Subject: location cut off on profile link on dashboard on mobile 
Description:
Open dashboard on mobile. See screenshot 

Results:
Is this link to the dashboard needed, as there is access via the profile menu on the top right.
If needed - probably no need to show the location.

Backend version: develop-9d1e6fe7
Frontend version: develop-9d1e6fe7-next
User Agent: Mozilla/5.0 (Android 16; Mobile; rv:140.0) Gecko/140.0 Firefox/140.0
Screen resolution: 403x771
Page: https://next.couchershq.org/dashboard
User: [@chrisk](https://next.couchershq.org/user/chrisk) (178)

### LINKED ISSUE #6462: Join us button is hiding parts of footer on mobile
Subject: Join us button is hiding parts of footer on mobile
Description:
See screenshot

Results:

Backend version: develop-9d1e6fe7
Frontend version: develop-9d1e6fe7
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36
Screen resolution: 395x811
Page: https://couchers.org/
User: [@chrisk](https://couchers.org/user/chrisk) (34148)

### LINKED ISSUE #6463: Join us button should not show when logged in
Subject: Join us button should not show when logged in
Description:
See screenshot

Results:

Backend version: develop-9d1e6fe7
Frontend version: develop-9d1e6fe7
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36
Screen resolution: 395x811
Page: https://couchers.org/
User: [@chrisk](https://couchers.org/user/chrisk) (34148)

### PR DESCRIPTION
**Pull request by nabramow**
* Remove `localeDetection: true` (apparently it's true by default and wasn't working)
* Add middleware.ts file to properly handle defaulting to browser language if no NEXT_LOCALE cookie set yet (instructions how to test below)
* Fix mobile landing page footer cut off: Closes #6462 
* Don't show join us button when logged in: Closes #6463 
* location cut off on profile link on dashboard on mobile: Closes #6456 
* Fix translation page style for longer language names 
* Add translation strings for weblate language names
* Remove imports arranging conflict in settings.json

How locale detection should work
* If you already have a NEXT_LOCALE cookie, default to that 
* If you do not have a NEXT_LOCALE cookie, set it to the browser language

NOTE: On localhost it doesn't totally work as it sets the cookie for next.couchers.org due to the default stage environment

To test:

(sorry I only know chrome)
1. Go to Chrome>Settings>Languages and change your default language to German, move it to the top place
2. Open an incognito window and load the vercel link or localhost for this branch, it should default to the browser language (German)
3. Go to regular browser, select a language from the picker different than the browser
4. Refresh the page at the baseRoute: localhost:3000/ (remove the locale from the route)
5. It should default to your NEXT_LOCALE cookie language (not German)
6. Go change your chrome settings back

### CODE REVIEW

File: app/web/features/translate/LanguagePickerSelect.tsx [hunk 1]
```diff
@@ -80,6 +80,9 @@ export default function LanguagePickerSelect({
       await changeLanguageMutation(newLocale);
     }
 
+    // Set the NEXT_LOCALE cookie
+    document.cookie = `NEXT_LOCALE=${newLocale}; path=/; max-age=31536000; SameSite=Lax`;
```
Comment (aapeliv) [inline app/web/features/translate/LanguagePickerSelect.tsx]: If you are sending this to the backend, then it should be setting the cookie itself

File: app/web/next-i18next.config.js [hunk 2]
```diff
@@ -3,17 +3,12 @@ const { allLanguages } = require("./i18n/allLanguages");
 
 const fallbackLng = {
   default: ["en"],
-  "es-419": ["es", "en"],
-  "fr-CA": ["fr", "en"],
-  pt: ["pt-BR", "en"],
-  "pt-BR": ["pt", "en"],
-  "zh-Hant": ["zh-Hans", "en"],
+  zh: ["zh-Hans", "en"],
```
Comment (aapeliv) [inline app/web/next-i18next.config.js]: What are these changes?

File: app/web/next-i18next.config.js [hunk 3]
```diff
@@ -23,7 +18,6 @@ module.exports = {
   ns: NAMESPACES,
   returnEmptyString: false,
   serializeConfig: false,
-  nonExplicitSupportedLngs: true, // Handle language codes like "zh-CN" and "zh-Hant" fallback to zh gracefully
```
Comment (aapeliv) [inline app/web/next-i18next.config.js:26]: What does this do?

File: app/web/resources/locales/en.json [hunk 4]
```diff
@@ -224,5 +224,26 @@
...
+    "ja": "Japanese",
+    "nb-NO": "Norwegian (Bokmål)",
+    "pl": "Polish",
+    "pt": "Portuguese (Portugal)",
+    "pt-BR": "Portuguese (Brazil)",
+    "ru": "Russian",
+    "sv": "Swedish",
+    "uk": "Ukrainian",
+    "zh-Hans": "Chinese (Simplified)",
+    "zh-Hant": "Chinese (Traditional)"
```
Comment (aapeliv) [inline app/web/resources/locales/en.json:247]: Should the language names be in the languages themselves? I think it's much harder to pick e.g. English when the page is in Chinese

File: app/web/next-i18next.config.js (hunk 2 above)
Comment (nabramow) [reply app/web/next-i18next.config.js]: Okay I added some back. I was debating whether to use the key below or this, but the Chinese variants kinda messes up the logic and after researching this seems more performant for server-side rendering.

I will adjust it.

File: app/web/next-i18next.config.js (hunk 3 above)
Comment (nabramow) [reply app/web/next-i18next.config.js:26]: I had added this in a previous PR, just removing it again. I read the fallback languages are the more performant way to do it. It would have defaulted to the base language if no variant found.

File: app/web/resources/locales/en.json (hunk 4 above)
Comment (nabramow) [reply app/web/resources/locales/en.json:247]: Hmm you mean so always have them in the native name? Or English?

Comment (nabramow) [reply app/web/resources/locales/en.json:247]: @aapeliv Just FYI you know these are for the translation page right? Not the language picker (that uses flag and code):

Screenshot 2025-07-21 at 9 20 55 PM
