### PR TITLE
report content redirects to help center URL

### LINKED ISSUE #5303: Update bug reporting modal button to take user to Help Center "how to report a user/content" page
### Problem
The button `Report inappropriate content or behavior` on the bug report button just has a text which explains how to send an email to the support team. This is better than nothing, but the button should take the user to the Help Center page which explains to the user how to report the person or content that is problematic - and also explains how to contact the support team via email. Here is the button in question:
image
Ideally users will use the reporting features because it provides more context to the support team than just an email would.

### Solution
The button `Report inappropriate content or behavior` should take the user to the following Help Center page which explains how to use the reporting features OR send an email:

https://help.couchers.org/hc/couchersorg-help-center/articles/1715125657-how-do-i-report-someone-or-something-that-violates-the-community-guidelines-or-terms-of-use-to_u

### PR DESCRIPTION
**Pull request by shane-jeon**
Redirects user to [Help Center - "How can I report someone or something to the Safety Team?" page](https://help.couchers.org/hc/couchersorg-help-center/articles/1715125657-how-do-i-report-someone-or-something-that-violates-the-community-guidelines-or-terms-of-use-to_u) when "Report inappropriate content or behavior" button is clicked.
Added above URL to routes.ts
Closes #5303 

**Backend checklist**
- [ ] Formatted my code by running `ruff check --select I --fix . && ruff check . && ruff format .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [X] Formatted my code with `yarn format`
- [X] There are no warnings from `yarn lint --fix`
- [X] There are no console warnings when running the app
- [x] Added tests where relevant
- [x] All tests pass
- [X] Clicked around my changes running locally and it works
- [X] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

File: app/web/components/Navigation/ReportButton.tsx [hunk 1]
```diff
@@ -25,6 +18,7 @@ import { ReportBugRes } from "proto/bugs_pb";
 import { useState } from "react";
 import { useForm } from "react-hook-form";
 import { useMutation } from "react-query";
+import { helpCenterURL } from "routes";
```
Comment (nabramow) [inline app/web/components/Navigation/ReportButton.tsx]: Just had a look at this URL and compared with the ticket. The ticket gives a specific link, not the general URL, so I think you will want to add a new URL here like `helpCenterReportContentURL` and use the link listed in the ticket which is:

https://help.couchers.org/hc/couchersorg-help-center/articles/1715125657-how-do-i-report-someone-or-something-that-violates-the-community-guidelines-or-terms-of-use-to_u

Then make sure to switch those out!

Scroll down to the bottom of this file, you will see similar ones.

Comment (shane-jeon) [reply app/web/components/Navigation/ReportButton.tsx]: new URL added to routes.ts and replaced in ReportButton.tsx! thank you for double checking that

File: app/web/components/Navigation/ReportButton.tsx [hunk 2]
```diff
@@ -169,9 +170,11 @@ export default function ReportButton({
...
               </StyledReportTypeButton>
               <StyledReportTypeButton
-                onClick={() => {
-                  setType("content");
-                }}
+                // href={helpCenterReportContentURL}
+                onClick={() =>
+                  (window.location.href = helpCenterReportContentURL)
+                }
+                component="button"
```
Comment (nabramow) [inline app/web/components/Navigation/ReportButton.tsx]: I wouldn't adjust the code to the test, but rather update the test to account for the new code here. 

Please change this back to `href`, then in the failing test, the line for the content button that's failing, change the role from `button` to `link`.

If you look at the error the test spits out, it looks like this:

```
      link: // <== this one!

      Name "Report inappropriate content or behaviour":
      <a
        class="MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary css-12lrxmm-MuiButtonBase-root-MuiButton-root"
        href="https://help.couchers.org/hc/couchersorg-help-center/articles/1715125657-how-do-i-report-someone-or-something-that-violates-the-community-guidelines-or-terms-of-use-to_u"
        tabindex="0"
      />
```

That `link` at the top, is telling you the new role. You should be able to update the role (the href changes the button role to link under the hood in MUI) and the test will hopefully pass!

File: app/web/components/Navigation/ReportButton.tsx [hunk 3]
```diff
@@ -169,9 +170,11 @@ export default function ReportButton({
                 {t("report.bug.button_label")}
               </StyledReportTypeButton>
               <StyledReportTypeButton
-                onClick={() => {
-                  setType("content");
-                }}
```
Comment (nabramow) [inline app/web/components/Navigation/ReportButton.tsx:174]: Looks like this was the only place we're setting the `content` type and the `supportEmail`, so we can do a little clean up here too:

- Remove `content` from the type for the useState at the top of the component
- Remove the `type === content` conditional rendering logic
- Remove the import for `supportEmail` and any other unused imports in `ReportButton` file
- Search in VSCode for `supportEmail`, I think this was the last place we're using it. If so, please delete that constant from appConstants file.

**Review by nabramow — APPROVED** [review]
Okay this is looking good to me now and working well! Thanks for you patience with teh feedback. Merge away!
