### PR TITLE
Fix: Improve Label Alignment and Spacing in Profile View (Issue #4973)

### LINKED ISSUE #4973: age/gender looks weird on mobile
Subject: age/gender looks weird on mobile
Description:
Pixel 7 is the device
You can see it here
https://couchers.org/user/primuladinverno/about

Results:
The slash is like on a different line and it's all crunched together.

Backend version: develop-c13607f7
Frontend version: develop-c13607f7
User Agent: Mozilla/5.0 (Android 14; Mobile; rv:131.0) Gecko/131.0 Firefox/131.0
Page: https://couchers.org/user/primuladinverno/about
User: raybb (8119)

### PR DESCRIPTION
**Pull request by SarimFaraz**
### Closes #4973 

**Description:**
This pull request addresses the following improvements for the profile view:

- Fixes the issue of the text looking weird by breaking it into two separate lines in mobile view to remain consistent and readable
- Ensures proper top alignment of labels (e.g., "Occupation") with multi-line content.
- Fixes inconsistent spacing around the / separator in AgeAndGenderRenderer.
- Enhances responsive design to maintain proper spacing and alignment across desktop, mobile, and tablet screens.
- Refactors LabelAndText to improve layout and maintainability.

**Web frontend checklist**
- [x] There are no console warnings when running the app
- [x] Clicked around my changes running locally and it works
- [x] Checked Desktop, Mobile and Tablet screen sizes
- [x] Manually tested changes in the UI and confirmed functionality.

**Notes:**
No changes were made to the backend.
All changes were tested locally and worked as expected.

### CODE REVIEW

**Comment by nabramow** [comment]
@SarimFaraz Is this ready for review? If so feel free to change the status to "PR" on the right!

**Comment by SarimFaraz** [comment]
> @SarimFaraz Is this ready for review? If so feel free to change the status to "PR" on the right!

Hello, yes it is ready for review, but I am not able to change the status to PR.

File: app/web/features/profile/view/userLabels.tsx [hunk 1]
```diff
@@ -180,13 +180,20 @@ const AgeAndGenderRenderer = ({ user }: Props) => {
...
   };
   return (
-    <>
+    <div
+      style={{
+        display: "flex",
+        flexWrap: "wrap",
+        alignItems: "center",
+      }}
+    >
```
Comment (nabramow) [inline app/web/features/profile/view/userLabels.tsx]: Please add a class for this to the relevant `useStyles` and put the style there, to align with how we do CSS. You can see examples on other elements on this page, for example if you search `iconStyles`.

File: app/web/features/profile/view/userLabels.tsx [hunk 2]
```diff
@@ -180,13 +180,20 @@ const AgeAndGenderRenderer = ({ user }: Props) => {
...
       <span>{age}</span>
-      {getBirthdateVerificationIcon(birthdateVerificationStatus)} /&nbsp;
+      {getBirthdateVerificationIcon(birthdateVerificationStatus)}
+      <span>/&nbsp;</span>
```
Comment (nabramow) [inline app/web/features/profile/view/userLabels.tsx:191]: Is the goal to add a space after the icon? If so please do it via css.

Comment (SarimFaraz) [reply app/web/features/profile/view/userLabels.tsx:191]: The goal was to put a space after the number/symbol because I saw inconsistent styling. 
eg. It looked like this before: "28 /Man" and it looks like this with the change: "28 / Man"

**Comment by nabramow** [comment]
Can confirm the smushed over multiple lines is fixed.

Just one small thing, do we want spaces on both sides of the slash @jesseallhands ? My first thought is usually it doesn't have the spaces:

Screenshot 2024-12-09 at 8 30 46 AM

**Comment by jesseallhands** [comment]
> Just one small thing, do we want spaces on both sides of the slash @jesseallhands ? My first thought is usually it doesn't have the spaces:

My thoughts: For the pronouns I would say  we can remove the spaces since it's commonplace to omit the spaces in that particular situation (eg. she/her rather than she / her). Keep in mind that any other pronouns besides she/her and he/him are user-specified so we have no control there. The other usage with age and gender (eg. 29 / Woman) should have the spaces for readability (I think 29/Woman looks a bit squished?)

**Comment by SarimFaraz** [comment]
> > Just one small thing, do we want spaces on both sides of the slash @jesseallhands ? My first thought is usually it doesn't have the spaces:
> 
> My thoughts: For the pronouns I would say we can remove the spaces since it's commonplace to omit the spaces in that particular situation (eg. she/her rather than she / her). Keep in mind that any other pronouns besides she/her and he/him are user-specified so we have no control there. The other usage with age and gender (eg. 29 / Woman) should have the spaces for readability (I think 29/Woman looks a bit squished?)

This is resolved in the newest commit.

Note: Just to add, the spaces in the pronouns already existed before I started working on this issue.

**Comment by SarimFaraz** [comment]
@nabramow, Would it be possible to add my team members to this pull request: @mrahmed2026, @safa-amin, @mayTkhin24, @FatimaHad

**Comment by nabramow** [comment]
> @nabramow, Would it be possible to add my team members to this pull request: @mrahmed2026, @safa-amin, @mayTkhin24, @FatimaHad

Hey @SarimFaraz, that's not something I myself can do. Whoever makes the commit shows up as the author. If you're pair-programming, you can co-author a commit following these instructions:
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Review by nabramow — APPROVED** [review]
Looks good now, approving! Thanks for working on this!

**Comment by aapeliv** [comment]
@SarimFaraz please merge you're happy to

**Comment by SarimFaraz** [comment]
> @SarimFaraz please merge you're happy to
Screenshot 2024-12-10 at 9 39 05 PM
Hi Aapeli, I am unable to merge. I attached a screenshot of what it shows.

**Comment by aapeliv** [comment]
Ah okay, no worries. I'll merge.
