### PR TITLE
Map (react) fixes

### LINKED ISSUE #446: Pressing enter on MapSearch (EditUserLocationMap) should search, but it submits instead
The `<form>` onSubmit triggers and MapSearch onSubmit does not for some reason.

### LINKED ISSUE #447: EditUserLocationMap search result should be fudged
For people who search their exact address and don't bother to move the circle, the lat/lng results of search should be randomised a bit.

### PR DESCRIPTION
**Pull request by lucaslcode**
closes #447 and closes #446

### CODE REVIEW

File: app/frontend/src/features/profile/ProfileForm.tsx [hunk 1]
```diff
@@ -88,124 +90,126 @@ export default function EditProfileForm() {
...
-                  <TextField
-                    {...params}
-                    helperText="Press 'Enter' to add"
-                    label="Languages"
-                  />
-                )}
-              />
-            )}
-          />
+          <form onSubmit={onSubmit}>
```
Comment (darrenvong) [inline app/frontend/src/features/profile/ProfileForm.tsx:93]: How come we need to split this into two forms?

Comment (lucaslcode) [reply app/frontend/src/features/profile/ProfileForm.tsx:93]: It seemed to be the only way I could get "enter" to not submit the whole form (the map is excluded from the form)

Comment (darrenvong) [reply app/frontend/src/features/profile/ProfileForm.tsx:93]: That means the user can now submit with only their username if they press enter, not sure if we want to allow that 🤔

Comment (lucaslcode) [reply app/frontend/src/features/profile/ProfileForm.tsx:93]: Wdym? It seems to work for me. If I change some fields including name and click enter while typing there, all fields are correctly submitted. 

I couldn't find another way - tried seeing if I could detect the field from `handleSubmit` but it only gives the submit button as the source.

Comment (darrenvong) [reply app/frontend/src/features/profile/ProfileForm.tsx:93]: What I meant was when you type a new user name then press enter with it focused, it would submit the form. I thought that would only submit the username field on its own but it looks like `useForm` seems to deal with that quite well and correctly forwards all the existing data on the page on too.

File: app/frontend/src/components/MapSearch.tsx [hunk 2]
```diff
@@ -112,36 +112,42 @@ export default function MapSearch({
```
Comment (darrenvong) [inline app/frontend/src/components/MapSearch.tsx:112]: Probably nitpick - but can we rename the props `city` and `setCity` instead of `value` and `setValue`? That matches what it's called in the parent and makes it a bit more obvious I think what kinda value is setting.

**Review by darrenvong — APPROVED** [review]
None blocking nitpick and probably semi-obvious considering it's in a MapSearch component. But I thought no harm in renaming to make it even more obvious and also helps tracing what gets pass down the tree more quickly from a glance if the name matches up (for me anyway).

File: app/frontend/src/components/MapSearch.tsx (hunk 2 above)
Comment (lucaslcode) [reply app/frontend/src/components/MapSearch.tsx:112]: This was on purpose because it might be used for any kind of location. In fact, it's "city" which is poorly named, but that's what it is called in the protobuf.
