### PR TITLE
Mobile fixes v1.1.16 - signup confirmation and staging asset links

### LINKED ISSUE #8041: Can't confirme my mail
Subject: Can't confirme my mail
Description:
Hello i tried with 2 of my mail adress but when they send me the link to confirm my mail adress it do nothing .. 

Results:

Backend version: develop-7ee4bb3e
Frontend version: develop-7ee4bb3e
User Agent: Mozilla/5.0 (Linux; Android 12; M2101K6G Build/SKQ1.210908.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36
Screen resolution: 392x791
Page: https://couchers.org/login
User: <not logged in>

### PR DESCRIPTION
**Pull request by nabramow**
Closes #8041 

- Add confirm-email route to the allowed non logged out routes for mobile to fix signup confirmation
- Add asset links for staging app so staging will also redirect to app if installed (so we can replicate these kinda things on staging app)
- Add user agent string for bug reports

## For maintainers

- [x] Maintainers can push commits to my branch
- [x] Maintainers can merge this PR for me

### CODE REVIEW

File: app/mobile/app/_layout.tsx [hunk 1]
```diff
@@ -76,6 +76,8 @@ function RootNavigator({ fontsLoaded }: { fontsLoaded: boolean }) {
       <Stack.Protected guard={!authenticated}>
         <Stack.Screen name="login" />
       </Stack.Protected>
+      {/* Unprotected routes — accessible regardless of auth state */}
+      <Stack.Screen name="confirm-email" />
```
Comment (aapeliv) [inline app/mobile/app/_layout.tsx:82]: I think we also need `signup`, `confirm-email`, `complete-password-reset`
