### PR TITLE
logout on unauthenticated error

### LINKED ISSUE #439: Authentication logic is broken
You can get stuck "phantom logged in" if the backend invalidates your session but the frontend doesn't. The frontend won't update the state to unauthenticated if it gets back an unauthenticated response from the server.

One way to reproduce:
1) Navigate to https://app.couchers.org and log in
2) Navigate to https://develop--frontend.preview.coucher.org and log in
3) Log out of https://app.couchers.org (this will remove the cookies)
4) Now https://develop--frontend.preview.coucher.org is phantom logged in

Possibly easier:
1) Go to https://develop--frontend.preview.coucher.org and log in
2) Remove cookies for domain api.couchers.org
3) You're now phantom logged in

### PR DESCRIPTION
**Pull request by lucaslcode**
Closes #439

### CODE REVIEW

File: app/frontend/src/service/client.ts [hunk 1]
```diff
@@ -8,9 +9,34 @@ import { SSOPromiseClient } from "../pb/sso_grpc_web_pb";
 
 const URL = process.env.REACT_APP_API_BASE_URL;
 
+let _unauthenticatedErrorHandler: (e: object) => void = () => {};
+export const setUnauthenticatedErrorHandler = (f: (e: object) => void) => {
+  _unauthenticatedErrorHandler = f;
+};
```
Comment (lucaslcode) [inline app/frontend/src/service/client.ts]: @darrenvong your favourite 😈 

But seriously, I can't think of a better way since interceptors are outside the tree and we're using context now.

Comment (darrenvong) [reply app/frontend/src/service/client.ts]: Lol dunno what to say about it at this point 😂 

This kinda feels worse than when we read from the Redux store as that's also global and outside of React so there won't be any chance of setting states on an unmounted component. But I suppose this won't be a problem if we clean it up in the `useEffect` cleanup function.

An alternative would be to handle the error within our custom `useX` query hook's query function to avoid this. Since all of these calls would be back under the context tree again, we shouldn't have to worry about the problem mentioned above.

File: app/frontend/src/features/auth/AuthProvider.tsx [hunk 2]
```diff
@@ -13,6 +16,19 @@ function useAppContext<T>(context: Context<T | null>) {
...
+
+  useEffect(
+    () =>
+      setUnauthenticatedErrorHandler(() => {
+        store.authActions.logout();
+        store.authActions.authError("You were logged out.");
+        push(loginRoute);
+      }),
+    [push, store.authActions]
+  );
```
Comment (darrenvong) [inline app/frontend/src/features/auth/AuthProvider.tsx]:
```suggestion
  useEffect(
    () => {
      setUnauthenticatedErrorHandler(() => {
        store.authActions.logout();
        store.authActions.authError("You were logged out.");
        push(loginRoute);
      });

      return () => {
        setUnauthenticatedErrorHandler(() => {});
      };
    },
    [push, store.authActions]
  );
```
Might be best to clean up the effect by unsetting the handler to a noop function to reduce any possibility of a memory leak if you are sticking with this solution...

**Review by darrenvong — CHANGES_REQUESTED** [review]

File: app/frontend/src/service/client.ts (hunk 1 above)
Comment (darrenvong) [reply app/frontend/src/service/client.ts]: After more thoughts, I think I prefer handling errors within the each query route more as this file is essentially a black box that we can't test easily since we've been mocking it out completely, so it'd be nice to avoid putting any logic here.

Comment (lucaslcode) [reply app/frontend/src/service/client.ts]: That's true, but I a bit hesitant to put `if unauthenticated, log out` every time we use the API. It's code duplication and prone to forgetting.

Maybe we should use mobx? Or would that still have the same issue - we would be able to call functions on the store outside the react tree, but it would still be logic in this file.

Comment (darrenvong) [reply app/frontend/src/service/client.ts]: Yeah MobX would solve the memory issue but not the testability issue.

I think creating an [auth error boundary](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html), have the logout logic there and use it to wrap the rest of the app might be the best way to go. This might be the rare case where we'll have to use a class component as error boundaries component still doesn't have an equivalent in function component AFAIK!

Comment (darrenvong) [reply app/frontend/src/service/client.ts:15]: Speaking of which, this would be a nice place to put some generic "sorry, we encountered some issues" UI rather than letting the app crash for errors that we might not have seen before and so don't have a specific strategy to handle it, so I think this is a good idea.

Comment (lucaslcode) [reply app/frontend/src/service/client.ts]: Won't that still require logic in every hook? Because at the moment, the error is caught and displayed in an alert, so it won't make it to the error boundary.

Comment (darrenvong) [reply app/frontend/src/service/client.ts]: Isn't the error is only caught because of this interceptor? I was thinking if you don't catch it here, React Query doesn't have error handling if the service promise throws

Comment (darrenvong) [reply app/frontend/src/service/client.ts]: ~~If you mean the existing Redux code then yeah, will probably have to remove the catches and let it propagate to the error boundary, but should be ok if we are eventually dismantling it anyway?~~

Oh never mind, I guess you mean the components that catch its own errors because it has a local error display, hmm yeah that would probably mess it up 🤔

Comment (lucaslcode) [reply app/frontend/src/service/client.ts]: You know what, I will try removing all the alerts and just put one above the router and catch there. Individual components can then still catch if they need to for a particular reason but in general they don't I think

Comment (lucaslcode) [reply app/frontend/src/service/client.ts]: After experimenting some more, still haven't come up with a solution. Error boundaries don't catch errors in async logic. You can [use a fake 'setState' inside `catch`](https://medium.com/trabe/catching-asynchronous-errors-in-react-using-error-boundaries-5e8a5fd7b971), but you have to put that in every component. It would apparently work in concurrent mode, but that is still experimental.

I agree it's bad to have this mystery bit that is mocked out and will not be tested. Maybe the question is, do we prefer 10 or so lines of untested code or putting `authActions.checkForAuthError(error)` in every hook? I keep going back and forth thinking about it...

Comment (darrenvong) [reply app/frontend/src/service/client.ts]: I didn't know that but makes sense when explained in that post, so that's good to know.

And yeah, I'm torn about this too, although I'm leaning more towards repetition so we can test this and have increased confidence that things work as intended.  It's one extra line if extracted into a function and most of these custom query hooks will probably need some error handling anyway so I think it's tolerable.

Comment (darrenvong) [reply app/frontend/src/service/client.ts]: I think this also brings into question our testing strategy - the fact that we completely mock this out means that if we do have a legit use case where things would only work with interceptors, we can't use them with confidence due to the lack of tests.

Maybe we work harder on only mocking the `client.<grpcMethod>()` would be a better answer, because that way, we can still check interceptors are applied correctly and the clients are called with the right params etc. They seem like an elegant tool we lose/can't use confidently because we're "slacking" on our tests.

Comment (lucaslcode) [reply app/frontend/src/service/client.ts]: What about just testing `AuthInterceptor.intercept`? We can mock the `invoker` and pass it in. We could also mock `setUnauthenticatedErrorHandler` and test the useEffect in `useAuthStore`. So, testing the two halves seperately. An integration test of them together would be very difficult, I think.

Comment (darrenvong) [reply app/frontend/src/service/client.ts]: I don't think it'd be too difficult (although probably awkward since we'll have to work with those `*Res` classes...) since the grpc methods on the client returns back an object rather than a buffer response.

Otherwise, the `setUnauthenticatedErrorHandler` mock is a bit better since it tests the useEffect sets the right thing and we'll have to assume the blackbox works from that point on.

Not sure I'd bother with testing the `AuthInterceptor` if you mean calling `intercept` directly with a mocked `invoker` succeeding/throwing etc, since everything is so instrumented at that point and it's not how the code uses it, I don't see much value in maintaining extra tests for that. Testing the client with the grpc methods mocked (we don't care about its response) would be better as we can see it's using the interceptor correctly.

Comment (lucaslcode) [reply app/frontend/src/service/client.ts]: I'm not sure it would work (or I'm not understanding). The clients are created with `new XPromiseClient(opts)` which is library code and `opts` contains the interceptor which runs mysteriously in the library. I don't see what you could mock to make it work easily.

Comment (darrenvong) [reply app/frontend/src/service/client.ts]: If we let it run as usual, unless I overlooked something, the only reason it'd fail would be because it's trying to make network calls right? So if we can mock enough to stop it trying to hit a real API, the rest of the code should run fine?

Comment (lucaslcode) [reply app/frontend/src/service/client.ts]: Yes, but that would involve mocking grpc-web internals. Not sure where to start, even looking at the source!

Comment (lucaslcode) [reply app/frontend/src/service/client.ts]: For now I did the `setUnauthenticatedErrorHandler` mock test

Comment (darrenvong) [reply app/frontend/src/service/client.ts]: I'd have thought mocking the grpc methods on the client's prototype would be enough, as I assume that's where it starts making requests?

File: app/frontend/src/service/client.ts [hunk 3]
```diff
@@ -8,9 +9,36 @@ import { SSOPromiseClient } from "../pb/sso_grpc_web_pb";
 
 const URL = process.env.REACT_APP_API_BASE_URL;
 
+let _unauthenticatedErrorHandler: (e: object) => void = () => {};
```
Comment (darrenvong) [inline app/frontend/src/service/client.ts]:
```suggestion
let _unauthenticatedErrorHandler: () => Promise<void> = () => {};
```
Wouldn't this be fine, since nothing gets passed through the useEffect callback? Also the return type should match the one in the setter?

File: app/frontend/src/service/client.ts (hunk 1 above)
Comment (lucaslcode) [reply app/frontend/src/service/client.ts]: You can do that, but it won't use the interceptor. [That happens here!](https://github.com/grpc/grpc-web/blob/e88fdc809d9ccbf1c9dae701ee14cce53be38b9e/javascript/net/grpc/web/grpcwebclientbase.js#L103)

File: app/frontend/src/service/client.ts (hunk 3 above)
Comment (lucaslcode) [reply app/frontend/src/service/client.ts]: I was passing the error anyway in case for future use, but yeah it won't be necessarily.

File: app/frontend/src/service/client.ts (hunk 1 above)
Comment (darrenvong) [reply app/frontend/src/service/client.ts]: Wow, that's annoying, the whole grpc library is such a pile of 💩  I guess we are screwed in with the blackbox then 😢

Comment (darrenvong) [reply app/frontend/src/service/client.ts]: Actually after looking at their implementation, I changed my mind about what I said on not unit testing the interceptor, since it doesn't look like they're doing anything special other than calling them all in a loop.

So if we do and our logic is tested, we can go off the assumption the blackbox works since any deeper mocking will mean we're testing their code and we shouldn't do that. 

I'm happy to wrap this up after that's done!

**Review by darrenvong — COMMENTED** [review]
No tests for the interceptor? Or are you doing it separately?

**Comment by lucaslcode** [comment]
How should I test it? Just test the class without going through gRPC? I will do that

**Review by darrenvong — APPROVED** [review]
