### PR TITLE
Fixing minor visual bugs

### LINKED ISSUE #606: Visual bugs
Poked around on iOS 14.4, mobile Safari, iPhone 11 Pro.

* The main content overflows under the bottom menu bar on every page (the "Save" button here is partly hidden):

signal-2021-02-08-164731_003

* Initiating host request has these empty blobs for start/end dates.

signal-2021-02-08-164731_001

* Missing space under this message:

signal-2021-02-08-164731_002

### PR DESCRIPTION
**Pull request by Tay0108**
Closes #606.

There is one problem - date picking is not a visual bug - Chrome has its own component for doing date picking, Safari does not. Should I replace those TextFields with some MaterialUI DatePicker?

### CODE REVIEW

**Comment by lucaslcode** [comment]
Thanks, will check this out tonight!

#495 is related to the dates and would fix that I'm guessing, so if you wanted to work on that it could be another PR.

File: app/frontend/src/App.tsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ import { theme } from "./theme";
 
 const useStyles = makeStyles((theme) => ({
   padding: {
-    paddingBottom: theme.spacing(7),
+    paddingBottom: theme.spacing(10),
```
Comment (lucaslcode) [inline app/frontend/src/App.tsx:20]: How did you choose 10? This will conflict with my PR awaiting review and I did 9 (can't remember why) but I could change it to 10.

**Review by lucaslcode — APPROVED** [review]

File: app/frontend/src/features/messages/surfing/NewHostRequest.tsx [hunk 2]
```diff
@@ -112,14 +117,16 @@ export default function NewHostRequest() {
...
           />
-          <Button
-            type="submit"
-            color="primary"
-            onClick={onSubmit}
-            loading={mutation.isLoading}
-          >
-            Send
-          </Button>
+          <div className={classes.buttonContainer}>
```
Comment (lucaslcode) [inline app/frontend/src/features/messages/surfing/NewHostRequest.tsx]: use `Box`

**Review by lucaslcode — CHANGES_REQUESTED** [review]

File: app/frontend/src/App.tsx (hunk 1 above)
Comment (Tay0108) [reply app/frontend/src/App.tsx:20]: I chose 10 because in figma there is 16px gap between navigation and button. Navigation has 64px (doesn't matter what device I check on) so if I put 10 `padding-bottom` evaluates to 80px (64+16). But what I did not see is that in Figma navigation is slightly bigger (73px). So it's up to you ;)

File: app/frontend/src/features/messages/surfing/NewHostRequest.tsx (hunk 2 above)
Comment (Tay0108) [reply app/frontend/src/features/messages/surfing/NewHostRequest.tsx]: Should I replace every `buttonContainer` `div` with `Box`? I did not introduce it, seen this div wrapper in some component so I thought I will copy for consistency.

Comment (lucaslcode) [reply app/frontend/src/features/messages/surfing/NewHostRequest.tsx]: Just change this one for now and we can decide what to do overall and fix the others later

**Review by lucaslcode — APPROVED** [review]
