### PR TITLE
code organization, navbar overhaul, add friend button

### LINKED ISSUE #754: Navigation tweaks
On mobile, search is hidden and bug report button is inaccessible off the screen

### LINKED ISSUE #759: Profile action buttons
Friend Request - should only be visible when appropriate (eg. send friend request button only if they aren't friends already).

### LINKED ISSUE #760: Account settings page
- A page to hold the links/forms for changing password, email, gender.
- Remove those links from the bottom of profile page
- Link to this page from somewhere that makes sense

### PR DESCRIPTION
**Pull request by andreaowu**
#754 #760 #759 

Screen Shot 2021-03-09 at 9 02 41 AM
Screen Shot 2021-03-09 at 9 03 22 AM
Screen Shot 2021-03-09 at 9 03 30 AM

(I keep pushing onto the wrong branch so that's why this PR came with three different fixes, oops)

**Friends**
My profile
Screen Shot 2021-03-11 at 8 24 39 PM

"Add friend" button clicked, and then:
Screen Shot 2021-03-11 at 8 24 47 PM

Did not try to add friend:
Screen Shot 2021-03-11 at 8 24 54 PM

### CODE REVIEW

File: app/frontend/src/components/Navigation/NavButton.tsx [hunk 1]
```diff
@@ -22,17 +18,38 @@ const useStyles = makeStyles((theme) => ({
...
+  label: {
+    alignSelf: "center",
+    marginTop: 0,
+  },
 }));
 
+interface NavButtonProps {
+  route: string;
+  label: string;
+  labelVariant:
```
Comment (lucaslcode) [inline app/frontend/src/components/Navigation/NavButton.tsx]: Can this variant type be imported from mui?

File: app/frontend/src/components/Navigation/Navigation.tsx [hunk 2]
```diff
@@ -1,68 +1,60 @@
...
+  {
     name: "Messages",
     route: messagesRoute,
   },
   {
-    icon: <LocationIcon fontSize="inherit" />,
-    name: "Map",
-    route: mapRoute,
+    name: "Communities",
+    route: communityRoute,
```
Comment (lucaslcode) [inline app/frontend/src/components/Navigation/Navigation.tsx]: Should we leave this as the map until communities are in?

File: app/frontend/src/components/Navigation/Navigation.tsx [hunk 3]
```diff
@@ -76,32 +68,77 @@ const useStyles = makeStyles((theme) => ({
...
 
 export default function Navigation() {
   const classes = useStyles();
-
   const authenticated = useAuthContext().authState.authenticated;
+  const [open, setOpen] = React.useState(false);
+
+  const logoutButton = <NavButton route={logoutRoute} label={LOG_OUT} />;
+
+  const drawer = (
```
Comment (lucaslcode) [inline app/frontend/src/components/Navigation/Navigation.tsx]:
```suggestion
  const drawerItems = (
```
Since it's not the whole drawer

File: app/frontend/src/components/Navigation/Navigation.tsx [hunk 4]
```diff
@@ -119,38 +156,67 @@ export default function Navigation() {
...
+              aria-label="open drawer"
+              onClick={handleDrawerOpen}
+              edge="start"
+            >
+              <MenuIcon />
+            </IconButton>
+            <Drawer
+              variant="temporary"
+              anchor="left"
+              open={open}
```
Comment (lucaslcode) [inline app/frontend/src/components/Navigation/Navigation.tsx:174]: this needs a `handleClose` prop so clicking the overlay closes the drawer

File: app/frontend/src/features/profile/functions/useUpdateHostingPreferences.test.tsx [hunk 5]
```diff
@@ -1,5 +1,5 @@
 import { renderHook } from "@testing-library/react-hooks";
-import useUpdateHostingPreferences from "features/profile/useUpdateHostingPreferences";
+import useUpdateHostingPreferences from "features/profile/functions/useUpdateHostingPreferences";
```
Comment (lucaslcode) [inline app/frontend/src/features/profile/functions/useUpdateHostingPreferences.test.tsx]: thoughts on "hooks" folder name instead of "functions"? I think "hooks" is more common, but it should be obvious they are hooks because of the name "use*"

File: app/frontend/src/components/Navigation/Navigation.tsx [hunk 6]
```diff
@@ -119,38 +156,67 @@ export default function Navigation() {
...
-          classes={{
-            root: classes.flex,
-          }}
-        >
-          {menu.map((item) => (
-            <NavButton
-              route={item.route}
-              label={item.name}
-              key={`${item.name}-nav-button`}
+          <Hidden mdDown>
```
Comment (lucaslcode) [inline app/frontend/src/components/Navigation/Navigation.tsx]:
```suggestion
          <Hidden smDown>
```

File: app/frontend/src/components/Navigation/Navigation.tsx [hunk 7]
```diff
@@ -119,38 +156,67 @@ export default function Navigation() {
...
+            <Grid
```
Comment (lucaslcode) [inline app/frontend/src/components/Navigation/Navigation.tsx]: This `<Grid container>` has no `<Grid item>` children, so maybe it can just be a div?

**Review by lucaslcode — CHANGES_REQUESTED** [review]
Was there a verdict in slack in the end? We can discuss it at the frontend meeting too

File: app/frontend/src/components/Navigation/NavButton.tsx (hunk 1 above)
Comment (andreaowu) [reply app/frontend/src/components/Navigation/NavButton.tsx]: I couldn't find what type it is :(

File: app/frontend/src/components/Navigation/Navigation.tsx (hunk 2 above)
Comment (andreaowu) [reply app/frontend/src/components/Navigation/Navigation.tsx]: We're going to have to change it later, so might as well just change it now?

Comment (lucaslcode) [reply app/frontend/src/components/Navigation/Navigation.tsx]: Yes, but if we do the soft beta thing, it might still not be in yet

File: app/frontend/src/components/Navigation/NavButton.tsx (hunk 1 above)
Comment (lucaslcode) [reply app/frontend/src/components/Navigation/NavButton.tsx]: What is the type of the `variant` prop of `Typography`?

Comment (andreaowu) [reply app/frontend/src/components/Navigation/NavButton.tsx]: Dunno, I just put what I saw on the [docs](https://material-ui.com/api/typography/#props)

**Review by lucaslcode — DISMISSED** [review]
Sorry for not picking this up before, but there needs to be top padding or content is covered by the header on mobile (use/change `theme.shape.navPaddingMobile`). This only happens on some pages for some reason (dashboard and profile)

File: app/frontend/src/components/Navigation/NavButton.tsx (hunk 1 above)
Comment (darrenvong) [reply app/frontend/src/components/Navigation/NavButton.tsx]: `Exclude<TypographyProps['variant'], undefined>` should do it. The utility type is needed because `variant` is optional on `TypographyProps` and we probably don't want `undefined` to be a possible value here.

File: app/frontend/src/AppRoute.tsx [hunk 8]
```diff
@@ -17,6 +17,7 @@ export const useStyles = makeStyles((theme) => ({
       paddingTop: theme.shape.navPaddingDesktop,
     },
     paddingBottom: theme.shape.navPaddingMobile,
```
Comment (lucaslcode) [inline app/frontend/src/AppRoute.tsx]:
```suggestion
```

File: app/frontend/src/components/Navigation/Navigation.tsx [hunk 9]
```diff
@@ -72,36 +63,82 @@ const useStyles = makeStyles((theme) => ({
...
+  const [open, setOpen] = React.useState(false);
+
+  const logoutButton = <NavButton route={logoutRoute} label={LOG_OUT} />;
+
+  const drawerItems = (
+    <div>
+      <List>
+        {menu.map(({ name, route }) => (
+          <ListItem button key={name}>
+            <NavButton route={route} label={name} labelVariant="h2" />
```
Comment (lucaslcode) [inline app/frontend/src/components/Navigation/Navigation.tsx:127]: I think the drawer needs to close on click. Maybe a `closeDrawer` prop for `NavButton`?

File: app/frontend/src/theme.ts [hunk 10]
```diff
@@ -57,7 +57,7 @@ const themeOptions: ThemeOptions = {
   shape: {
     borderRadius,
     navPaddingDesktop: spacing(10),
-    navPaddingMobile: spacing(8),
+    navPaddingMobile: spacing(10),
```
Comment (lucaslcode) [inline app/frontend/src/theme.ts]: This should exactly be the navbar height (3.5), some pages may not want padding between the bar and content (for example, if there is a banner image)

File: app/frontend/src/features/profile/view/Overview.tsx [hunk 11]
```diff
@@ -75,12 +78,20 @@ export default function Overview({ user }: OverviewProps) {
...
-      {user.userId === currentUserId && (
+      {user.userId === currentUserId ? (
         <CardActions className={classes.cardActions}>
           <Button component={Link} to={editProfileRoute}>
             {EDIT_PROFILE}
           </Button>
         </CardActions>
+      ) : (
+        <CardActions className={classes.cardActions}>
+          {mutationError && <Alert severity="error">{mutationError}</Alert>}
```
Comment (lucaslcode) [inline app/frontend/src/features/profile/view/Overview.tsx]: This should be outside `CardActions`, or it looks funny when it is present

File: app/frontend/src/features/profile/view/Overview.tsx [hunk 12]
```diff
@@ -75,12 +78,20 @@ export default function Overview({ user }: OverviewProps) {
...
+          <AddFriendButton
+            userId={user.userId}
+            setMutationError={setMutationError}
+          />
+        </CardActions>
```
Comment (lucaslcode) [inline app/frontend/src/features/profile/view/Overview.tsx]: There should be a check here for `user.friendshipStatus`, showing this on `NOT_FRIENDS`, maybe a grayed out pending button for `PENDING` (actually maybe nothing for now, that will be quicker) and nothing for `FRIENDS`

**Review by lucaslcode — DISMISSED** [review]
Last one sorry!

File: app/frontend/src/components/Navigation/NavButton.tsx (hunk 1 above)
Comment (andreaowu) [reply app/frontend/src/components/Navigation/NavButton.tsx]: How did you find out what the type is?

Comment (darrenvong) [reply app/frontend/src/components/Navigation/NavButton.tsx]: VS Code shows you if you write out something like `type Variant = TypographyProps['variant']` and hover over where it says `TypographyProps['variant']`. Or you can click on `TypographyProps` and it should jump you into that file with the type definition

Comment (andreaowu) [reply app/frontend/src/components/Navigation/NavButton.tsx]: Sounds good, thanks!

File: app/frontend/src/theme.ts (hunk 10 above)
Comment (andreaowu) [reply app/frontend/src/theme.ts]: Why do some pages not want padding between bar and content? (Which pages wouldn't want that?)

Comment (lucaslcode) [reply app/frontend/src/theme.ts]: Communities page wouldn't because of the banner image

Comment (andreaowu) [reply app/frontend/src/theme.ts]: It's bad design if we need to go to every page to add spacing due to one page not wanting that spacing?

Comment (lucaslcode) [reply app/frontend/src/theme.ts]: Fair, how about separating Nav bar height and Nav bar padding variables so in those instances, we can do a negative margin accurately (or is there a better way?)

Comment (lucaslcode) [reply app/frontend/src/theme.ts]: Fair, how about separating Nav bar height and Nav bar padding variables so in those instances, we can do a negative margin accurately (or is there a better way?)

**Review by lucaslcode — APPROVED** [review]
