### PR TITLE
Fix login issues with email

### LINKED ISSUE #1279: Can't log in with e-mail
Subject: Can't log in with e-mail
Description:
I tried logging in with my email in the Email/Username field and my password (which has worked before in the beta), but I got a "Cannot Find this User" error message.  I could log in with my username.

Results:
I should be able to log in using either an email or a username... right?

Backend version: develop-7f962c9e
Frontend version: develop-7f962c9e
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
Page: https://app.couchers.org/
User (spoofable): natalia (198)

### PR DESCRIPTION
**Pull request by aapeliv**
Add user_id to AuthRes so that frontend doesn't have to do an extra query to get the user right after logging in.

Ought to fix #1279 

**Backend checklist**
- [ ] Formatted my code by running `isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

File: app/frontend/src/features/auth/useAuthStore.ts [hunk 1]
```diff
@@ -73,12 +73,8 @@ export default function useAuthStore() {
         setLoading(true);
         try {
           const auth = await service.user.passwordLogin(username, password);
+          setUserId(auth.userId);
 
-          if (!auth.jailed) {
-            const user = await service.user.getUser(username);
-            setUserId(user.userId);
-            queryClient.setQueryData(["user", user.userId], user);
```
Comment (darrenvong) [inline app/frontend/src/features/auth/useAuthStore.ts:80]: I just looked at how this differs from `getCurrentUser` - `getCurrentUser` calls the `Ping` rpc to get the current user, so I think we could do the same here and we wouldn't even need to change the API?

**Review by lucaslcode — COMMENTED** [review]
How does this fix the problem? And how was frontend showing the wrong message?

**Review by darrenvong — APPROVED** [review]

**Comment by aapeliv** [comment]
> How does this fix the problem? And how was frontend showing the wrong message?

It was calling `API.GetUser` as soon as the user had logged in (to get the user's ID): but it was using `username` from the login input which was really the user's email. `GetUser` no longer supports getting users by email (even the current user), so this was failing.

I saw that it was doing two requests when logging in because the frontend wants the user id in its state, so I thought it would be better to just return it in one request.

**Comment by darrenvong** [comment]
> How does this fix the problem?

There's a semi-recent (?) change to the API that stops you from getting a user using an email and when the user logs in with username/email and password, in the frontend it was using the email to get the current user as soon as they are authenticated and so triggering the "cannot find this user" error message from the backend

**Comment by darrenvong** [comment]
Lol looks like we were typing that at around the same time and Aapeli beats me to it 😄
