### PR TITLE
fix `ProfileTagInput` zIndex clash

### LINKED ISSUE #1956: "Region I've lived in" toggle is broken
Subject: "Region I've lived in" toggle is broken
Description:
Edit your profile and try to select a country in the "Region I've lived in" toggle.

Results:
Nothing happens. It should have selected the country.
The "Region's I've visited" toggle works fine.

Backend version: develop-4dc3cf58
Frontend version: develop-4dc3cf58
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
Page: https://app.couchers.org/profile/edit/about
User: thomasahle (4229)

### LINKED ISSUE #1964: Can't choose countries lived in
Subject: Can't choose countries lived in
Description:
Tried choosing a button from dropdown menu.

Results:
It doesn't let us choose additional countries.

Backend version: develop-4dc3cf58
Frontend version: develop-4dc3cf58
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
Page: https://app.couchers.org/profile/references
User: bk007 (4243)

### LINKED ISSUE #1968: Regions and Additional information clash
Subject: Regions and Additional information clash
Description:
On my profile page I first filled out Additional information and then started registering regions I've visited. The Additional information box was in WYSIWYG mode at that time.

Results:
With the Additional information box in WYSIWYG mode, the selection widget for countries only responded after only one country matches the typed name. I expect it to be fully clickable. 
When the Additional information box is in Markdown mode  it works much better.

Backend version: develop-4dc3cf58
Frontend version: develop-4dc3cf58
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0
Page: https://app.couchers.org/profile/edit/about
User: louisbroekhuijsen (4282)

### PR DESCRIPTION
**Pull request by lucaslcode**
This fixed the problem in prod when I made the equivalent changes in devtools, but no idea why the bug exists in prod but not dev.

fix #1956 fix #1964 fix #1968

### CODE REVIEW

File: app/web/src/features/profile/ProfileTagInput.tsx [hunk 1]
```diff
@@ -87,7 +87,7 @@ const useStyles = makeStyles((theme) =>
       borderWidth: 1,
       boxShadow: theme.shadows[3],
       marginTop: theme.spacing(1),
-      zIndex: 1,
+      zIndex: 101,
```
Comment (darrenvong) [inline app/web/src/features/profile/ProfileTagInput.tsx:90]: Why 101 specifically?

Comment (lucaslcode) [reply app/web/src/features/profile/ProfileTagInput.tsx:90]: ToastUI uses 50 (or was it 30), I thought it was good to give some wiggle room

**Review by darrenvong — APPROVED** [review]
