### PR TITLE
Fixed stretched community event image

### LINKED ISSUE #5077: Event images distorted on events page
Currently the images on the [events page](https://couchers.org/events) are distorted:

image

To fix this, we should probably resize the image (to avoid high-res images from being overcropped), center the image, and crop it.

### PR DESCRIPTION
**Pull request by fbalda**
Fixed a bug where event card images in the events tab of a community page were stretched to fit the thumbnail size and rendered entirely incorrectly on small screen sizes.

**Web frontend checklist**
- [x] Formatted my code with `yarn format`
- [x] There are no warnings from `yarn lint --fix`
- [x] There are no console warnings when running the app
- [x] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [x] Checked Desktop, Mobile and Tablet screen sizes

**Other**
*Untick the following if you'd prefer that maintainers don't push commits/merge your branch.*
- [x] A maintainer can push commits to my branch
- [x] A maintainer can merge my PR (you can also merge after approval)

### CODE REVIEW

**Comment by nabramow** [comment]
I think this is connected to this ticket?

https://github.com/Couchers-org/couchers/issues/5077

If so feel free to assign that to yourself and connect it to this PR.

File: app/web/features/communities/events/LongEventCard.tsx [hunk 1]
```diff
@@ -128,9 +128,8 @@ const LongEventCard = ({
           image={event.photoUrl || eventImagePlaceholderUrl}
           title={event.title}
           sx={{
-            height: "100%",
-            width: "25%",
-            objectFit: "fill",
```
Comment (nabramow) [inline app/web/features/communities/events/LongEventCard.tsx:133]: The `objectFit: "fill"` makes the `eventImagePlacholderUrl` not get expanded and cut off. Without it now it looks like this:

Screenshot 2025-08-02 at 4 40 38 PM

We want it to look like this (gray background is just because I'm hovering ignore that):

Screenshot 2025-08-02 at 4 50 44 PM

**Comment by nabramow** [comment]
While you're in there, would you mind checking if you can fix the stretched event image as well? Looks like this:

Screenshot 2025-08-02 at 4 53 44 PM


Hint: If you go to EditEventPage, it looks okay. Just the regular EventPage is stretching it for some reason.

Here is the image file I am using to replicate:

Partners-Flat-White-FT-BLOG0523-b11f6273c2d84462954c2163d6a1076d

File: app/web/features/communities/events/LongEventCard.tsx (hunk 1 above)
Comment (fbalda) [reply app/web/features/communities/events/LongEventCard.tsx:133]: Good catch, I missed that

**Comment by fbalda** [comment]
Addressed the previous comments and also converted the `EventPage` to styled while I was at it, as I needed to change the styling anyway

File: app/web/features/communities/events/EventPage.tsx [hunk 2]
```diff
@@ -41,105 +40,113 @@ import EventOrganizers from "./EventOrganizers";
 import { useEvent } from "./hooks";
 import InviteCommunityDialog from "./InviteCommunityDialog";
 
-export const useEventPageStyles = makeStyles<Theme, { eventImageSrc: string }>(
-  (theme) => ({
-    eventCoverPhoto: {
-      height: 100,
-      [theme.breakpoints.up("md")]: {
-        height: 200,
-      },
```
Comment (nabramow) [inline app/web/features/communities/events/EventPage.tsx:50]: Is this the last place these were used? Seems so!

File: app/web/features/communities/events/LongEventCard.tsx [hunk 3]
```diff
@@ -128,9 +128,9 @@ const LongEventCard = ({
...
+            objectFit: event.photoUrl ? "none" : "contain",
```
Comment (nabramow) [inline app/web/features/communities/events/LongEventCard.tsx]:
```suggestion
            objectFit: event.photoUrl ? "cover" : "contain",
```

Otherwise it looks like this:
Screenshot 2025-08-03 at 9 49 57 AM

File: app/web/features/communities/events/EventPage.tsx (hunk 2 above)
Comment (fbalda) [reply app/web/features/communities/events/EventPage.tsx:50]: Yeah it is 🎉

File: app/web/features/communities/events/LongEventCard.tsx (hunk 3 above)
Comment (fbalda) [reply app/web/features/communities/events/LongEventCard.tsx]: Oops, yeah that makes much more sense

**Review by nabramow — APPROVED** [review]
Good to go! 🚀
